### PR TITLE
Meowbot Secret Santa Functionality!!!

### PR DESCRIPTION
**Pull request by shellychw**
This pull request  implements feature #52 Secret Santa as stated in the issue description.

Changes:
-  Change MeowBot.kt to have a singleton object Meowbot and all of the DiscordClientGateway stuff is stored that and can be access through the MeowBot class
- New event listener for secret santa

Note: Ahh I didn't deal with null checks too well so I dunno if that is gonna be a problem.

### CODE REVIEW

**Comment by lwise** [comment]
Hey, I think you can avoid importing the `client` into other classes (separation of concerns blah blah) by using code along these lines:
```kotlin
            val member = responseVector.guild.getMemberById(receivers[i]).block()!!
            val memberUsername = member.username
            // We might be able to use this one
            member.privateChannel.block().createMessage()
            // If the top one works that's good. If not then you can do this.
            // But I'd rather not subscribe to something we don't actually need to listen for any replies.
            member.privateChannel.subscribe {
                // blah blah blah
            }
```

**Comment by shellychw** [comment]
Removed the changes in Moewbot.kt.
Query Member object from Guild in ResponseVector

**Review by lwise — APPROVED** [review]
nice LGTM!!!!

**Comment by shellychw** [comment]
Merged!! ❤️

**Pull request merged**
